### ISSUE TITLE
Integration Causes Poor Performance After Upgrade to Home Assistant Core 2024.7.x

### ISSUE THREAD

**Issue by brwyatt** [dcmeglio/homeassistant-petsafe#16]
It appears that on 2024.7.0 and 2024.7.1 (at the time of this writing), this integration causes more than double CPU usage and causes the web UI for HA to be non-responsive and slow. Disabling this integration returns the CPU usage and responsiveness back to normal.

See [this issue](https://github.com/home-assistant/core/issues/121327) for Home Assistant Core reporting this problem.

In my case, upgrading to 2024.7.0 resulted in the CPU usage going from 4-12% (pre-upgrade) up to 26-33%. Disabling this integration returned CPU usage back to normal.

**Comment by dcmeglio** [comment]
I can reproduce the issue but not sure what's going on yet.

**Comment by stefanoklett** [comment]
I have noticed a general slowdown in HASS for more than a month now. 
Only now have I disabled the integrations one by one and I find that this is what is slowing it down.
I have no idea why, so I keep it disabled for now, too bad,

My current release: 2024.7.4

**Comment by dcmeglio** [comment]
Unfortunately https://github.com/dcmeglio/homeassistant-petsafe/issues/15 did not fix this. I haven't yet been able to track down what changed in HA to cause this since the integration hasn't been touched in over a year. Still trying to figure it out. Still happening in the 2024.8 betas as well

**Comment by hco** [comment]
If you haven't tried already, I had good experiences with asking for help in the home assistant discord. Maybe someone can point to to something that has changed in the core? 🤔

**Comment by Axsgranted** [comment]
If it helps, i was the originator of the Core thread.  Not sure if you saw the specific log entry that was, supposedly causing the issues:

2024-07-05 13:51:00.490 DEBUG (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/appconfigdata',) inside the event loop by custom integration 'petsafe' at custom_components/petsafe/init.py, line 244: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 311: api_versions = os.listdir(full_dirname)), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues

**Comment by dcmeglio** [comment]
@hco yeah I had asked already. Unfortunately the underlying library I was using for authentication (to AWS Cognito) has a bug which the author listed as "won't fix" https://github.com/aio-libs/aiobotocore/issues/1023 so I have to rewrite it to use a different library. Doable, just a bit more work than a simple fix.

**Comment by dcmeglio** [comment]
I've got a fix in testing. Seems to be working but I want to do a little more playing around. I'm taking this opportunity to make a few other performance improvements too

**Comment by hco** [comment]
If you want an alpha-tester, let me know. I am a software developer, but no expert in python. I've managed to do some changes in HA integrations, though, and have created one-and-a-half integrations on my own.

**Comment by dcmeglio** [comment]
https://github.com/dcmeglio/homeassistant-petsafe/releases/tag/1.3.2 should resolve this issue, I've been running it for 3 days now and CPU has not spiked above 15% and has been averaging around 11%. I think this is fixed.

**Comment by hco** [comment]
Re-installed the plugin and HA felt sluggish again for me, so think the issue still exists for me :/

My monitoring also suggest it

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/8e629944-f250-4e95-ac72-58121b536e96">

**Comment by stefanoklett** [comment]
Yes, it is still slow.
Simple test, turn on a shelly light it can take up to 14sec.
If I disable it works immediately.
I would say it is not solved, so it remains disabled.
Regards
Stefano

**Comment by dcmeglio** [comment]
I’ll need logs and details. It is working perfectly for me now.

**Comment by Gr8fuldamned** [comment]
I am still seeing the high CPU usage as well.

Here are the log entries related.
`Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 8:10:33 AM (4 occurrences)
Last logged: 8:10:37 AM

Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data',) inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 246: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 306: for d in os.listdir(possible_path)), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/petsafe/__init__.py", line 195, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2098, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2109, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2111, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2191, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/petsafe/sensor.py", line 19, in async_setup_entry feeders = await coordinator.get_feeders() File "/config/custom_components/petsafe/__init__.py", line 246, in get_feeders self._feeders = await self.api.get_feeders()
Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/connect',) inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 246: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 311: api_versions = os.listdir(full_dirname)), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/petsafe/__init__.py", line 195, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2098, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2109, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2111, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2191, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/petsafe/sensor.py", line 19, in async_setup_entry feeders = await coordinator.get_feeders() File "/config/custom_components/petsafe/__init__.py", line 246, in get_feeders self._feeders = await self.api.get_feeders()
Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/cognito-idp',) inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 246: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 363: for dirname in os.listdir(possible_path):), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/petsafe/__init__.py", line 195, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2098, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2109, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2111, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2191, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/petsafe/sensor.py", line 19, in async_setup_entry feeders = await coordinator.get_feeders() File "/config/custom_components/petsafe/__init__.py", line 246, in get_feeders self._feeders = await self.api.get_feeders()
Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/botocore/data/cognito-idp/2016-04-18/service-2.json.gz', 'rb') inside the event loop by custom integration 'petsafe' at custom_components/petsafe/__init__.py, line 246: self._feeders = await self.api.get_feeders() (offender: /usr/local/lib/python3.12/gzip.py, line 192: fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/petsafe/__init__.py", line 195, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2098, in async_forward_entry_setups await self._async_forward_entry_setups_locked(entry, platforms) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2109, in _async_forward_entry_setups_locked await asyncio.gather( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2111, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2191, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 130, in async_setup_entry return await component.async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/petsafe/sensor.py", line 19, in async_setup_entry feeders = await coordinator.get_feeders() File "/config/custom_components/petsafe/__init__.py", line 246, in get_feeders self._feeders = await self.api.get_feeders()`

**Comment by dcmeglio** [comment]
Huh. That indicates it didn’t update. That code is no longer there

**Comment by Gr8fuldamned** [comment]
> Huh. That indicates it didn’t update. That code is no longer there

Interesting... shows that it is version 1.3.2.

I will try removing it completely and reinstalling.

**Comment by Gr8fuldamned** [comment]
I completely removed the integration, restarted Home Assistant, installed from HACS, restarted Home Assistant, set up the integration and am still seeing the errors in my logs and high CPU usage.

Here is the error that occurred:
`Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 10:36:18 AM (4 occurrences)
Last logged: 10:36:22 AM

Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data',) inside the event loop by custom integration 'petsafe' at custom_components/petsafe/config_flow.py, line 118: await self._client.request_code() (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 306: for d in os.listdir(possible_path)), please create a bug report at https://github.com/dcmeglio/homeassistant-petsafe/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 456, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/petsafe/config_flow.py", line 59, in async_step_user await self.get_email_code(user_input[CONF_EMAIL]) File "/config/custom_components/petsafe/config_flow.py", line 118, in get_email_code await self._client.request_code()`

Looks like the same error...

**Comment by dcmeglio** [comment]
Weird. I will look later tonight and ask for some more troubleshooting steps. I’ve had it running for 4 days, no more blocking call messages.

**Comment by hco** [comment]
@dcmeglio shouldn‘t this be 2.0.5?
https://github.com/dcmeglio/homeassistant-petsafe/blob/a4c85d969d97541db354ff1065256795bc733f85/custom_components/petsafe/manifest.json#L8

sorry if this is a stupid question, I‘m really not fluent in the python ecosystem. 😊

**Comment by Gr8fuldamned** [comment]
> @dcmeglio shouldn‘t this be 2.0.5?
> 
> https://github.com/dcmeglio/homeassistant-petsafe/blob/a4c85d969d97541db354ff1065256795bc733f85/custom_components/petsafe/manifest.json#L8
> 
> sorry if this is a stupid question, I‘m really not fluent in the python ecosystem. 😊

I tried this and it seems to be working! Current CPU usage is at normal expected levels and the integration is up and running!

**Comment by dcmeglio** [comment]
Not a stupid question! That’s the issue. I updated it locally but didn’t commit it. Will do it in a few hours

**Comment by dcmeglio** [comment]
1.3.3 published now which correctly uses 2.0.5 of the library. This should resolve the issue.

**Comment by brwyatt** [comment]
Can confirm, 1.3.2 still had the issue, and 1.3.3 fixes it. Get an initial CPU spike to 30% for about 15 seconds when it starts up, then returns to normal (expected) levels.

Thanks for taking a look and fixing this!

**Comment by stefanoklett** [comment]
I confirm with 1.3.3 it worsks fine.
Many thanks

**Comment by Gr8fuldamned** [comment]
Working perfect! Thank you!
